---
language: python
services: docker
jobs:
  include:
    - name: "(Debian/Ubuntu) Install NGINX Unit and NGINX Unit modules"
      env:
        scenario: default
    - name: "(Alpine) Install NGINX Unit and NGINX Unit modules"
      env:
        scenario: default_alpine
    - name: "(CentOS) Install NGINX Unit and NGINX Unit modules"
      env:
        scenario: default_centos
before_install: sudo apt-get -qq update
install:
  - pip install ansible==2.9.12
  - pip install molecule==3.0.6
  - pip install docker==4.2.2
  - pip install ansible-lint==4.3.0
script:
  - molecule --version
  - ansible --version
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
