---
- name: Setup prerequisites
  include_tasks: "{{ role_path }}/tasks/prerequisites/setup-{{ ansible_facts['os_family'] | lower }}.yml"
  tags: nginx_unit_prerequisites

- name: Setup keys
  include_tasks: keys/setup-keys.yml
  when:
    - ansible_facts['os_family'] in ['Debian', 'RedHat']
    - nginx_unit_enable | bool
  tags: nginx_unit_key

- name: Install NGINX Unit
  include_tasks: "{{ role_path }}/tasks/unit/install-unit.yml"
  when: nginx_unit_enable | bool
  tags: nginx_unit_install
