---
- name: (Debian/Ubuntu) Install dependencies
  apt:
    name: "{{ nginx_unit_debian_dependencies }}"
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: (Amazon Linux/CentOS/RHEL) Install dependencies
  yum:
    name: "{{ nginx_unit_redhat_dependencies }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: (FreeBSD) Install dependencies
  block:
    - name: (FreeBSD) Install dependencies using package(s)
      pkgng:
        name: "{{ nginx_unit_freebsd_dependencies }}"
      when: nginx_bsd_install_packages | bool

    - name: (FreeBSD) Install dependencies using port(s)
      portinstall:
        name: "{{ item }}"
        use_packages: "{{ nginx_unit_bsd_portinstall_use_packages | default(omit) }}"
      loop: "{{ nginx_unit_freebsd_dependencies }}"
      when: not nginx_bsd_install_packages | bool
  when: ansible_facts['distribution'] == "FreeBSD"
