---
- name: (FreeBSD) fetch ports
  command: portsnap fetch --interactive
  args:
    creates: /var/db/portsnap/INDEX

- name: (FreeBSD) Extract ports
  command: portsnap extract
  args:
    creates: /usr/ports
