---
- name: "(Install: Debian/Ubuntu) Add NGINX Unit Repository"
  apt_repository:
    filename: nginx-unit
    repo: "{{ item }}"
    update_cache: yes
    mode: 0644
  loop:
    - deb [arch=amd64] https://packages.nginx.org/unit/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} unit
    - deb-src https://packages.nginx.org/unit/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} unit
