---
- name: "(Debian/Ubuntu) Add NGINX Unit repository"
  apt_repository:
    filename: nginx-unit
    repo: "{{ item }}"
    update_cache: yes
    mode: 0644
  loop:
    - deb [arch=amd64] https://packages.nginx.org/unit/{{ ansible_facts['distribution'] | lower }}/ {{ ansible_facts['distribution_release'] }} unit
    - deb-src https://packages.nginx.org/unit/{{ ansible_facts['distribution'] | lower }}/ {{ ansible_facts['distribution_release'] }} unit
