---
name: Molecule CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    ignore-tags:
      - "*"
  schedule:
    - cron: "0 0 1 * *"
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scenario:
          - default
          - default_centos
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.x

      - name: Install Molecule dependencies
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible base dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_ansible.yml

      - name: Uninstall Ansible community distribution (temporary)
        run: pip3 uninstall -y ansible

      - name: Run Molecule tests
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
